refactor: Add unit testing and refactor code to follow Python standards.
cybcon/modbus-server pull request #31
Opened 2024-02-05 19:37 UTC by bvanelli

Hello @cybcon , I started writing this code on the last Hackergarten, but did not had the time to push it yet.

You wrote the integration test with the other part of the code. This tests how the applications work together, but it's too broad to test small functions inside the code. This PR adds the basic structure for unit testing too.

I also included other changes, here is the full changelog:

- Reformat file with community standards black, ruff and isort, with basic config. Black and ruff are formatters that make sure the code follows a stricter coding style. isort on the other hand makes sure the imports are sorted correctly.
- Format all variable namings using [PEP8](https://peps.python.org/pep-0008/). Here, I mostly took the suggestions from Pycharm, and some of it was done directly by black + ruff.
- Add two example unit tests for the part of the code that is currently testable.
- Add testing on CI using github actions and pytest. This makes sure the test would run on pull requests and on main branch.
- Improve code clarity by using f-strings, available since python 3.6. This should keep the complexity of writing custom logs much lower and improve readability.

I had to change some of the logic to make sure the code was testable by reducing the functions complexity, so some functions might be slightly different.

Let me know what you think and what you suggest.

2024-02-06 08:45 UTC, cybcon requested changes

2024-02-06 08:45 UTC, cybcon commented on src/app/modbus_server.py
> +    if not pathlib.Path(config_file).is_file():
Why using pathlib.Path().is_file() instead of os.path.isfile()?

2024-02-06 09:01 UTC, cybcon commented
Hi @bvanelli 
Thank you for this great contribution!

2024-02-06 20:40 UTC, bvanelli commented on .github/workflows/test.yaml
> +          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
Github actions uses ubuntu which should install without any problems. I added a line to change folders before running tests.

I also applied all your suggestions, maybe now the pipeline will go through.

2024-02-14 06:48 UTC, cybcon requested changes
Python test pipeline still fail.
In step pytest we get following error:
```
============================= test session starts ==============================
platform linux -- Python 3.9.18, pytest-8.0.0, pluggy-1.4.0
rootdir: /home/runner/work/modbus-server/modbus-server
collected 0 items / 2 errors

==================================== ERRORS ====================================
____________________ ERROR collecting tests/test_server.py _____________________
ImportError while importing test module '/home/runner/work/modbus-server/modbus-server/tests/test_server.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_server.py:2: in <module>
    from src.app.modbus_server import prepare_register
src/app/modbus_server.py:17: in <module>
    from pymodbus.datastore import (
E   ModuleNotFoundError: No module named 'pymodbus'
_____________________ ERROR collecting tests/test_utils.py _____________________
ImportError while importing test module '/home/runner/work/modbus-server/modbus-server/tests/test_utils.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_utils.py:2: in <module>
    from src.app.modbus_server import get_ip_address
src/app/modbus_server.py:17: in <module>
    from pymodbus.datastore import (
E   ModuleNotFoundError: No module named 'pymodbus'
=========================== short test summary info ============================
ERROR tests/test_server.py
ERROR tests/test_utils.py
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!
============================== 2 errors in 0.10s ===============================
```

2024-02-15 18:49 UTC, bvanelli commented
> Python test pipeline still fail. In step pytest we get following error:
> 
> ```
> ============================= test session starts ==============================
> platform linux -- Python 3.9.18, pytest-8.0.0, pluggy-1.4.0
> rootdir: /home/runner/work/modbus-server/modbus-server
> collected 0 items / 2 errors
> 
> ==================================== ERRORS ====================================
> ____________________ ERROR collecting tests/test_server.py _____________________
> ImportError while importing test module '/home/runner/work/modbus-server/modbus-server/tests/test_server.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/importlib/__init__.py:127: in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> tests/test_server.py:2: in <module>
>     from src.app.modbus_server import prepare_register
> src/app/modbus_server.py:17: in <module>
>     from pymodbus.datastore import (
> E   ModuleNotFoundError: No module named 'pymodbus'
> _____________________ ERROR collecting tests/test_utils.py _____________________
> ImportError while importing test module '/home/runner/work/modbus-server/modbus-server/tests/test_utils.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/importlib/__init__.py:127: in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> tests/test_utils.py:2: in <module>
>     from src.app.modbus_server import get_ip_address
> src/app/modbus_server.py:17: in <module>
>     from pymodbus.datastore import (
> E   ModuleNotFoundError: No module named 'pymodbus'
> =========================== short test summary info ============================
> ERROR tests/test_server.py
> ERROR tests/test_utils.py
> !!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!
> ============================== 2 errors in 0.10s ===============================
> ```

I had the conditional wrong, could you try again?

2024-02-27 13:19 UTC, cybcon approved these changes

2024-02-27 13:20 UTC, merged